package constants

const VERSION_1 = "v1"

var VERSIONS = []string{VERSION_1}

const TYPE_CLIENT = "client"
const TYPE_SERVER = "server"

var TYPES = []string{TYPE_CLIENT, TYPE_SERVER}

const ENDPOINT_TYPE_BUFFER = "buffer"
const ENDPOINT_TYPE_QUEUE = "queue"

var ENDPOINT_TYPES = []string{ENDPOINT_TYPE_BUFFER, ENDPOINT_TYPE_QUEUE}

const PROTOCOL_SECURE = "secure"
const PROTOCOL_PLAIN = "plain"

var PROTOCOLS = []string{PROTOCOL_PLAIN, PROTOCOL_SECURE}

const CONTENT_TYPE_JSON = "json"
const CONTENT_TYPE_YAML = "yaml"
const CONTENT_TYPE_XML = "xml"
const CONTENT_TYPE_TEXT = "text"
const CONTENT_TYPE_BINARY = "binary"

var CONTENT_TYPES = []string{CONTENT_TYPE_JSON, CONTENT_TYPE_YAML, CONTENT_TYPE_XML, CONTENT_TYPE_TEXT, CONTENT_TYPE_BINARY}

const FIELD_VERSION = "VERSION"
const FIELD_AUTH = "AUTH"
const FIELD_KIND = "KIND"
const FIELD_CONTENT_TYPE = "CONTENT-TYPE"
const FIELD_CONTENT_LENGTH = "CONTENT-LENGTH"
const FIELD_METADATA_TYPE = "METADATA-TYPE"
const FIELD_METADATA_LENGTH = "METADATA-LENGTH"
const FIELD_ENDPOINT = "ENDPOINT"

var FIELDS = []string{FIELD_VERSION, FIELD_AUTH, FIELD_KIND, FIELD_CONTENT_TYPE, FIELD_CONTENT_LENGTH, FIELD_METADATA_TYPE, FIELD_METADATA_LENGTH}

const KIND_ACCEPT = "ACCEPT"
const KIND_ACKNOWLEDGE = "ACKNOWLEDGE"
const KIND_CLOSE = "CLOSE"
const KIND_CONNECT = "CONNECT"
const KIND_DATA = "DATA"
const KIND_ERROR = "ERROR"
const KIND_PULL = "PULL"
const KIND_PUSH = "PUSH"
const KIND_REJECT = "REJECT"
const KIND_RETRY = "RETRY"

var KINDS = []string{KIND_ACCEPT, KIND_ACKNOWLEDGE, KIND_CLOSE, KIND_CONNECT, KIND_DATA, KIND_ERROR, KIND_PULL, KIND_PUSH, KIND_REJECT, KIND_RETRY}

const ENDPOINT = "/msg"
